parameters:
#    ingesup_tp.example.class: Ingesup\TPBundle\Example

services:
#    ingesup_tp.example:
#        class: %ingesup_tp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
